name: Build Site

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.3"
          otp-version: "27"

      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Build Site
        run: mix site.build

      - name: Push to `site` branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: site
          FOLDER: output
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "{msg}"
